

DATA_ROOT = '/media/dwout/75F9-FA9C/1617-Data-Mining-2.0/project/data/'
# '/media/david/75F9-FA9C/1617-Data-Mining-2.0/project/data/'

FN_DATABASE_JSON = DATA_ROOT+'database.json'

DIR_WIKI_ROOT = DATA_ROOT+'wikipedia/'
DIR_WIKI_PAGES = DIR_WIKI_ROOT+'html_pages/'
FN_WIKI_DATABASE_RAW = DIR_WIKI_ROOT+'database_raw.json'
FN_WIKI_URLS_INITIAL = DIR_WIKI_ROOT+'initial_urls.csv'
FN_WIKI_URLS_DONE = DIR_WIKI_ROOT+'processed_urls.csv'
FN_WIKI_URLS_TO_DO = DIR_WIKI_ROOT+'unprocessed_urls.csv'

DIR_PUBCHEM_ROOT = DATA_ROOT+'pubchem/'
DIR_PUBCHEM_JSON_RAW = DIR_PUBCHEM_ROOT+'json_raw/'
FN_PUBCHEM_URLS = DIR_PUBCHEM_ROOT+'urls.csv'
FN_PUBCHEM_IDS = DIR_PUBCHEM_ROOT+'ids.csv'
FN_PUBCHEM_DATABASE_RAW = DIR_PUBCHEM_ROOT+'database_raw.json'
FN_PUBCHEM_DESCRIPTIONS = DIR_PUBCHEM_ROOT+'descriptions.json'

DIR_CHEMSPIDER_ROOT = DATA_ROOT+'chemspider/'
FN_CHEMSPIDER_URLS = DIR_CHEMSPIDER_ROOT+'urls.csv'

ALL_DIRS = [DATA_ROOT, DIR_WIKI_ROOT, DIR_WIKI_PAGES, DIR_PUBCHEM_ROOT, DIR_CHEMSPIDER_ROOT, DIR_PUBCHEM_JSON_RAW]
ALL_FILES = [FN_DATABASE_JSON, FN_WIKI_DATABASE_RAW, FN_WIKI_URLS_INITIAL, FN_WIKI_URLS_DONE, FN_WIKI_URLS_TO_DO,
             FN_PUBCHEM_URLS, FN_CHEMSPIDER_URLS, FN_PUBCHEM_IDS, FN_PUBCHEM_DATABASE_RAW]
